# Generated by Django 4.2.3 on 2023-07-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='sobrenome',
            new_name='surname',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='preco',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='estoque',
            new_name='stock',
        ),
        migrations.AddField(
            model_name='produto',
            name='type',
            field=models.CharField(default=0, max_length=20, verbose_name='type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='email'),
        ),
    ]
